theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 32

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
device = "wlp6s0"
ssid = false
signal_strength = false
ip = false
speed_up = false
speed_down = true
graph_up = false
graph_down = false
interval = 5
use_bits = false

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

