#!/bin/bash
#PREVIOUS_EXTERNAL_STATUS=$(xrandr --display :0 2>&1 | grep DP2-2 | awk '{print $2}')

IFS=" "
INTERNAL_DISPLAYS="eDP-1"
EXTERNAL_DISPLAYS="DP-1-1 DP-1-2"

display_status() {
    return $(xrandr --display :0 2>&1 | grep $1 | awk '{print $2}')
}

if [ $(display_status $EXTERNAL_DISPLAYS) == "connected" ]; then
    # the external monitor is no longer available, I turn on the laptop's
    logger "`date -u` The external monitor is no longer available, I turn on the laptop's"
    xrandr --output DP1-1 --off
    xrandr --output DP1-2 --off
    xrandr --output eDP-1 --auto
else
    # the external monitor has become available
    logger "`date -u` The external monitor has become available"
    # first I _add_ the external monitor...
    xrandr --display :0 --output DP2-2 --auto --a
    xrandr --display :0 --output eDP1 --off
fi
