#!/bin/sh -eu
lock() {
    # Take a screenshot
    scrot /tmp/screen_locked.png

    # Pixellate it
    mogrify -scale 10% -scale 1000% /tmp/screen_locked.png

    # Lock screen displaying this image.
    i3lock -e -f -i /tmp/screen_locked.png

    # Erase any evidence
    rm /tmp/screen_locked.png
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        systemctl suspend
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|reboot|shutdown}"
        exit 2
esac

exit 0
